name: flutter_application_gestion_viajes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  image_picker: ^1.2.0
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  http: ^1.1.0  # Para geocoding


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
